import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const store=new Vuex.Store({
  state:{
    resume:{
      name:'小花',
      work:'美丽的前台',
      personalInfo:{
        "性别":"女",
        "年龄":"24岁",
        "qq":"123456",
        "联系方式":"13737373737",
        "邮箱":"123@qq.com"
      },
      introduction:'我是一个什么什么样的人。哈哈哈哈。我是一个什么什么样的人。哈哈哈哈。我是一个什么什么样的人。哈哈哈哈。我是一个什么什么样的人。哈哈哈哈。',
      education:[
        "2012-2016年，xxx大学",
        "本科，xxx专业",
        "2012-2016年，xxx大学",
        "本科，xxx专业"
      ],
      projects:[
        {
          "name":"基于xx的web平台",
          "myRole":"UI设计",
          "startTime":"2017-1-1",
          "endTime":"2018-1-1",
          "content":[
            "项目职责：前端开发",
            "项目描述：项目描述项目描述项目描述项目描述项目描述项目描述项目描述"
          ]
        },
        {
          "name":"基于xx的web平台",
          "myRole":"UI设计",
          "startTime":"2017-1-1",
          "endTime":"2018-1-1",
          "content":[
            "项目职责：前端开发",
            "项目描述：项目描述项目描述项目描述项目描述项目描述项目描述项目描述"
          ]
        },
        {
          "name":"基于xx的web平台",
          "myRole":"UI设计",
          "startTime":"2017-1-1",
          "endTime":"2018-1-1",
          "content":[
            "项目职责：前端开发",
            "项目描述：项目描述项目描述项目描述项目描述项目描述项目描述项目描述"
          ]
        },
        {
          "name":"基于xx的web平台",
          "myRole":"",
          "startTime":"2017-1-1",
          "endTime":"2018-1-1",
          "content":[
            "项目职责：前端开发",
            "项目描述：项目描述项目描述项目描述项目描述项目描述项目描述项目描述",
            "链接: http://www.baidu.com"
          ]
        }
      ],
      works:[
        {
          "name":"xxx公司",
          "myRole":"UI设计",
          "startTime":"2017-1-1",
          "endTime":"2018-1-1",
          "content":[
            "项目职责：前端开发",
            "项目描述：项目描述项目描述项目描述项目描述项目描述项目描述项目描述"
          ]
        },
        {
          "name":"xxx公司",
          "myRole":"",
          "startTime":"2017-1-1",
          "endTime":"2018-1-1",
          "content":[
            "项目职责：前端开发",
            "项目描述：项目描述项目描述项目描述项目描述项目描述项目描述项目描述"
          ]
        }
      ],
      skills:[
        {
          "title":"UI设计",
          "description":[
            "熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。"
          ]
        },
        {
          "title":"UI设计",
          "description":[
            "熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。"
          ]
        },
        {
          "title":"UI设计",
          "description":[
            "熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。熟练使用PS,美院毕业。"
          ]
        },
        {
          "title":"UI设计2",
          "description":[
            "熟练使用PS2",
            "美院毕业2"
          ]
        }
      ]
    }

  },
  mutations:{

  }
})

export default store
